apiVersion: v1
kind: Config
clusters:
  - name: <cluster-name>
    cluster:
      certificate-authority-data: <certificate>
      server: https://api.<cluster-name>
users:
  - name: OIDCUser
    user:
      token: <token>
contexts:
  - name: <cluster-name>
    context:
      cluster: <cluster-name>
      namespace: <deploy-namespace>
      user: OIDCUser
current-context: <cluster-name>